
# cargo-vet audits file

[audits]

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2027-05-27"

[[trusted.encoding_rs_io]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-03"
end = "2027-05-27"

[[trusted.js-sys]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-05-27"

[[trusted.js-sys]]
criteria = "safe-to-deploy"
trusted-publisher = "github:wasm-bindgen/wasm-bindgen"
start = "2026-04-28"
end = "2027-05-27"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2027-05-27"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2027-05-27"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2027-05-27"

[[trusted.wasm-bindgen]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-05-27"

[[trusted.wasm-bindgen]]
criteria = "safe-to-deploy"
trusted-publisher = "github:wasm-bindgen/wasm-bindgen"
start = "2026-04-28"
end = "2027-05-27"

[[trusted.wasm-bindgen-macro]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-05-27"

[[trusted.wasm-bindgen-macro]]
criteria = "safe-to-deploy"
trusted-publisher = "github:wasm-bindgen/wasm-bindgen"
start = "2026-04-28"
end = "2027-05-27"

[[trusted.wasm-bindgen-macro-support]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-05-27"

[[trusted.wasm-bindgen-macro-support]]
criteria = "safe-to-deploy"
trusted-publisher = "github:wasm-bindgen/wasm-bindgen"
start = "2026-04-28"
end = "2027-05-27"

[[trusted.wasm-bindgen-shared]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2027-05-27"

[[trusted.wasm-bindgen-shared]]
criteria = "safe-to-deploy"
trusted-publisher = "github:wasm-bindgen/wasm-bindgen"
start = "2026-04-28"
end = "2027-05-27"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2027-05-27"

[[trusted.zmij]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2025-12-18"
end = "2027-05-27"
